# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6d02c2f32edd0bb921456e55308a8630eacf1ab447af10aeae43185a12178b61949b70f7f7c992f67685afbbfcf3b78a27aef3c5252eab44b61c658aee6688

test:
  secret_key_base: 998a0b88fd7ab0687e1aa54b39785723b1f2acbea00050fa68f3155adc15102647bccb7b61769232da5438a18ecda2fc1d5d1a469832911c4556ff676cc550f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
